spring:
  application:
    name: saynow-be
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

springdoc:
  paths-to-match: /api/v1/**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

saynow:
  ai:
    base-url: ${SAYNOW_AI_BASE_URL:http://43.202.146.182:8080}
