-- 3차 MVP 주제형 프리톡 세션과 품질 피드백 스키마로 전환한다.
ALTER TABLE categories ADD COLUMN display_order INT;
ALTER TABLE categories ADD COLUMN locked BOOLEAN;
ALTER TABLE categories ADD COLUMN lock_reason VARCHAR(50);

UPDATE categories
SET display_order = id,
    locked = CASE WHEN id = 1 THEN FALSE ELSE TRUE END,
    lock_reason = CASE WHEN id = 1 THEN NULL ELSE 'COMING_SOON' END,
    updated_at = CURRENT_TIMESTAMP;

UPDATE categories
SET name = 'Free Talk',
    display_order = 1,
    locked = FALSE,
    lock_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1;

UPDATE categories
SET name = 'Airport',
    display_order = 2,
    locked = TRUE,
    lock_reason = 'COMING_SOON',
    updated_at = CURRENT_TIMESTAMP
WHERE id = 2;

UPDATE categories
SET name = 'Hotel',
    display_order = 3,
    locked = TRUE,
    lock_reason = 'COMING_SOON',
    updated_at = CURRENT_TIMESTAMP
WHERE id = 3;

UPDATE categories
SET name = 'Restaurant',
    display_order = 4,
    locked = TRUE,
    lock_reason = 'COMING_SOON',
    updated_at = CURRENT_TIMESTAMP
WHERE id = 4;

ALTER TABLE categories ALTER COLUMN display_order SET NOT NULL;
ALTER TABLE categories ALTER COLUMN locked SET NOT NULL;

ALTER TABLE scenarios ADD COLUMN briefing TEXT;
ALTER TABLE scenarios ADD COLUMN conversation_goal VARCHAR(255);
ALTER TABLE scenarios ADD COLUMN total_question_count INT;
ALTER TABLE scenarios ADD COLUMN locked BOOLEAN;
ALTER TABLE scenarios ADD COLUMN lock_reason VARCHAR(50);

UPDATE scenarios
SET briefing = COALESCE(situation, goal),
    conversation_goal = goal,
    total_question_count = 4,
    locked = FALSE,
    lock_reason = NULL,
    updated_at = CURRENT_TIMESTAMP;

UPDATE scenarios
SET title = '음식 취향 이야기하기',
    briefing = '좋아하는 음식과 최근 먹었던 음식에 대해 이야기합니다.',
    conversation_goal = '음식 취향과 경험을 영어로 자연스럽게 설명할 수 있다.',
    display_order = 1,
    category_id = 1,
    total_question_count = 4,
    locked = FALSE,
    lock_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1;

UPDATE scenarios
SET title = '여행 경험 이야기하기',
    briefing = '가봤던 여행지와 기억에 남는 순간을 이야기합니다.',
    conversation_goal = '여행 경험과 감정을 영어로 자연스럽게 설명할 수 있다.',
    display_order = 2,
    category_id = 1,
    total_question_count = 4,
    locked = FALSE,
    lock_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 2;

UPDATE scenarios
SET title = '일상 루틴 이야기하기',
    briefing = '평소 하루 일과와 쉬는 방식에 대해 이야기합니다.',
    conversation_goal = '일상 습관과 선호를 영어로 자연스럽게 설명할 수 있다.',
    display_order = 3,
    category_id = 1,
    total_question_count = 4,
    locked = FALSE,
    lock_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 3;

UPDATE scenarios
SET locked = TRUE,
    lock_reason = 'COMING_SOON',
    total_question_count = 4,
    updated_at = CURRENT_TIMESTAMP
WHERE category_id <> 1;

ALTER TABLE scenarios ALTER COLUMN briefing SET NOT NULL;
ALTER TABLE scenarios ALTER COLUMN conversation_goal SET NOT NULL;
ALTER TABLE scenarios ALTER COLUMN total_question_count SET NOT NULL;
ALTER TABLE scenarios ALTER COLUMN locked SET NOT NULL;

CREATE TABLE scenario_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL,
    sequence INT NOT NULL,
    question_en VARCHAR(500) NOT NULL,
    question_ko VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_scenario_questions_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios (id),
    CONSTRAINT uk_scenario_questions_scenario_sequence UNIQUE (scenario_id, sequence)
);

INSERT INTO scenario_questions (scenario_id, sequence, question_en, question_ko, created_at, updated_at) VALUES
(1, 1, 'What is your favorite food? Why do you like it?', '가장 좋아하는 음식이 뭐예요? 왜 좋아하나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 'Do you cook often?', '요리는 자주 하나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 'What food did you eat recently?', '최근에 먹은 음식은 뭐였나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 4, 'Is there a food you want to try next?', '다음에 먹어보고 싶은 음식이 있나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 'Where did you travel recently?', '최근에 어디로 여행을 갔나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 2, 'What was the most memorable part of that trip?', '그 여행에서 가장 기억에 남는 순간은 뭐였나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 'Who did you go with?', '누구와 함께 갔나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 4, 'Where would you like to travel next?', '다음에는 어디로 여행 가고 싶나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 'What do you usually do in the morning?', '아침에 보통 무엇을 하나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 'How do you spend your free time?', '여가 시간은 어떻게 보내나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 'What part of your day do you enjoy the most?', '하루 중 어떤 시간이 가장 좋나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, 'Is there a routine you want to change?', '바꾸고 싶은 일상 루틴이 있나요?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS session_slot_statuses;
DROP TABLE IF EXISTS scenario_slots;

ALTER TABLE user_scenario_progress ADD COLUMN completed BOOLEAN;
ALTER TABLE user_scenario_progress ADD COLUMN completed_at TIMESTAMP(6);
UPDATE user_scenario_progress
SET completed = cleared,
    completed_at = CASE WHEN cleared THEN updated_at ELSE NULL END;
ALTER TABLE user_scenario_progress ALTER COLUMN completed SET NOT NULL;
ALTER TABLE user_scenario_progress DROP COLUMN cleared;

ALTER TABLE sessions ADD COLUMN started_at TIMESTAMP(6);
ALTER TABLE sessions ADD COLUMN abandoned_at TIMESTAMP(6);
UPDATE sessions SET started_at = created_at WHERE started_at IS NULL;
ALTER TABLE sessions ALTER COLUMN started_at SET NOT NULL;
ALTER TABLE sessions DROP COLUMN remaining_hearts;

ALTER TABLE session_turns ADD COLUMN scenario_question_id BIGINT;
ALTER TABLE session_turns ADD COLUMN answered_at TIMESTAMP(6);
ALTER TABLE session_turns ADD CONSTRAINT fk_session_turns_scenario_question
    FOREIGN KEY (scenario_question_id) REFERENCES scenario_questions (id);
ALTER TABLE session_turns DROP COLUMN next_question_target_slot_name;

ALTER TABLE session_feedbacks ADD COLUMN status VARCHAR(20);
ALTER TABLE session_feedbacks ADD COLUMN native_score INT;
ALTER TABLE session_feedbacks ADD COLUMN native_level_label VARCHAR(100);
ALTER TABLE session_feedbacks ADD COLUMN summary TEXT;
ALTER TABLE session_feedbacks ADD COLUMN generated_at TIMESTAMP(6);
ALTER TABLE session_feedbacks DROP COLUMN cleared;
ALTER TABLE session_feedbacks DROP COLUMN comprehension_score;
ALTER TABLE session_feedbacks DROP COLUMN feedback_summary;

ALTER TABLE turn_feedbacks ADD COLUMN status VARCHAR(20);
ALTER TABLE turn_feedbacks ADD COLUMN feedback_type VARCHAR(30);
ALTER TABLE turn_feedbacks ADD COLUMN korean_analogy TEXT;
ALTER TABLE turn_feedbacks ADD COLUMN correction_point TEXT;
ALTER TABLE turn_feedbacks ADD COLUMN correction_reason TEXT;
ALTER TABLE turn_feedbacks ADD COLUMN plus_one_expression VARCHAR(500);
ALTER TABLE turn_feedbacks ADD COLUMN praise_summary TEXT;
ALTER TABLE turn_feedbacks ADD COLUMN praise_reason TEXT;
ALTER TABLE turn_feedbacks ADD COLUMN generated_at TIMESTAMP(6);
ALTER TABLE turn_feedbacks DROP COLUMN feedback_required;
ALTER TABLE turn_feedbacks DROP COLUMN native_understanding;
ALTER TABLE turn_feedbacks DROP COLUMN native_language_interpretation;
ALTER TABLE turn_feedbacks DROP COLUMN better_expression;

CREATE UNIQUE INDEX IF NOT EXISTS uk_session_nps_responses_session
    ON session_nps_responses (session_id);

ALTER TABLE scenarios DROP COLUMN original_question;
ALTER TABLE scenarios DROP COLUMN translated_question;
ALTER TABLE scenarios DROP COLUMN goal;
ALTER TABLE scenarios DROP COLUMN situation;
ALTER TABLE scenarios DROP COLUMN ai_role;
ALTER TABLE scenarios DROP COLUMN emoji;
ALTER TABLE scenarios DROP COLUMN background_image;
ALTER TABLE scenarios DROP COLUMN heart;
