-- 앱 버전별 강제/소프트 업데이트 정책을 저장한다.
CREATE TABLE app_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform VARCHAR(20) NOT NULL,
    version_name VARCHAR(30) NOT NULL,
    build_number BIGINT NOT NULL,
    minimum_supported_build_number BIGINT NOT NULL,
    force_update_reason VARCHAR(500),
    soft_update_reason VARCHAR(500),
    release_note TEXT,
    store_url VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    released_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_app_versions_platform CHECK (platform IN ('IOS', 'ANDROID')),
    CONSTRAINT ck_app_versions_build_number CHECK (build_number > 0),
    CONSTRAINT ck_app_versions_minimum_supported_build_number CHECK (
        minimum_supported_build_number > 0
        AND minimum_supported_build_number <= build_number
    ),
    CONSTRAINT uk_app_versions_platform_build UNIQUE (platform, build_number)
);

CREATE INDEX idx_app_versions_platform_active_build
    ON app_versions (platform, active, build_number DESC);
