-- 2차 MVP 초기 스키마와 기본 시나리오 데이터를 생성한다.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    nickname VARCHAR(100),
    sub VARCHAR(255),
    provider VARCHAR(20),
    deleted_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_provider_sub UNIQUE (provider, sub)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    original_question VARCHAR(500) NOT NULL,
    translated_question VARCHAR(500) NOT NULL,
    goal VARCHAR(255) NOT NULL,
    emoji VARCHAR(20),
    background_image VARCHAR(500) NOT NULL,
    heart INT NOT NULL,
    display_order INT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_scenarios_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT uk_scenarios_category_display_order UNIQUE (category_id, display_order)
);

CREATE TABLE scenario_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_scenario_slots_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios (id),
    CONSTRAINT uk_scenario_slots_scenario_name UNIQUE (scenario_id, name)
);

CREATE TABLE user_scenario_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scenario_id BIGINT NOT NULL,
    cleared BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_scenario_progress_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_scenario_progress_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios (id),
    CONSTRAINT uk_user_scenario_progress_user_scenario UNIQUE (user_id, scenario_id)
);

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scenario_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    remaining_hearts INT NOT NULL,
    completed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_sessions_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios (id)
);

CREATE TABLE session_turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    ai_question VARCHAR(500) NOT NULL,
    translated_question VARCHAR(500) NOT NULL,
    user_utterance TEXT,
    sequence INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_session_turns_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT uk_session_turns_session_sequence UNIQUE (session_id, sequence)
);

CREATE TABLE session_slot_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    slot_name VARCHAR(80) NOT NULL,
    is_fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_session_slot_statuses_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT uk_session_slot_statuses_session_slot UNIQUE (session_id, slot_name)
);

CREATE TABLE session_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    cleared BOOLEAN NOT NULL,
    comprehension_score INT NOT NULL,
    feedback_summary TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_session_feedbacks_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT uk_session_feedbacks_session UNIQUE (session_id)
);

CREATE TABLE turn_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_feedback_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL,
    feedback_required BOOLEAN NOT NULL,
    native_understanding TEXT,
    native_language_interpretation TEXT,
    better_expression VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_turn_feedbacks_session_feedback FOREIGN KEY (session_feedback_id) REFERENCES session_feedbacks (id),
    CONSTRAINT fk_turn_feedbacks_turn FOREIGN KEY (turn_id) REFERENCES session_turns (id),
    CONSTRAINT uk_turn_feedbacks_feedback_turn UNIQUE (session_feedback_id, turn_id)
);

INSERT INTO categories (id, name, created_at, updated_at) VALUES
(1, 'Cafe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Airport', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Hotel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Restaurant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO scenarios (
    id, title, original_question, translated_question, goal, emoji, background_image,
    heart, display_order, category_id, created_at, updated_at
) VALUES
(1, '카페에서 주문하기', 'What would you like to order?', '무엇을 주문하시겠어요?', '원하는 음료를 자연스럽게 주문할 수 있다.', '☕', 'https://static.saynow.local/cafe-order.png', 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '카페에서 옵션 말하기', 'Would you like it hot or iced?', '따뜻한 음료로 드릴까요, 차가운 음료로 드릴까요?', '원하는 옵션을 자연스럽게 말할 수 있다.', '🥤', 'https://static.saynow.local/cafe-option.png', 3, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '카페에서 문제 해결하기', 'Is there a problem with your order?', '주문에 문제가 있나요?', '주문 문제를 자연스럽게 해결할 수 있다.', '🧾', 'https://static.saynow.local/cafe-problem.png', 3, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO scenario_slots (scenario_id, name, created_at, updated_at) VALUES
(1, 'drink', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'size', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'temperature', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'option', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'problem', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'request', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
