-- 사용자가 특정 세션에 제출한 NPS 평가를 저장하는 테이블을 생성한다.
CREATE TABLE session_nps_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    score INT NOT NULL,
    low_score_reason TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_session_nps_responses_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_session_nps_responses_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT uk_session_nps_responses_user_session UNIQUE (user_id, session_id),
    CONSTRAINT ck_session_nps_responses_score CHECK (score BETWEEN 1 AND 5)
);
